### ISSUE TITLE
Too good for hackathon submission

### ISSUE THREAD

**Issue by pranaygp** [FleetAdmiral/NBOHackathon_2017#1]
I noticed that this repo (currently) has no code.

I'm a big proponent for simplicity when it comes to projects, and I admire your work in the right direction. This project should definitely win the NBO Hackathon 2017 given the simplicity and ease of access that your project provides

Good luck and Godspeed

**Comment by FleetAdmiral** [comment]
@pranaygp Thank you for the wonderful insights, good sir. However, noting the sarcasm i must say that we find this a bit offensive and that acknowledge we cannot win with such an attitu-  
wait, what's this?  
i-im-impossible!  
![hackathon_nbo](https://cloud.githubusercontent.com/assets/13980635/25652140/4b4caf14-3004-11e7-934b-cc21e61fbbf7.jpg)

We won?!? 💯 🥇 💯 

T-thank you Pranay senpai :'''''D  

P.S: This was one of the 'Someone make a git repo' moments where everybody on the team just went ahead and made one each and we just randomly chose which one to use.  
  
P.P.S: Here's the real repo: [Victorius_Secret](https://github.com/mukulhase/NBO)

**Comment by pranaygp** [comment]
I love functions named after people

```js
// RIP
function pranav(){
     if(input.includes("balance"))
    {
        balance = 4000; //TODO get balance
        if (balance>1000)
            str_end = "Looking good!"
        elsei
            str_end = "Looking edgy. Top up ASAP!"
    ...
```
Also, that's actually pretty sick! What did you win?

EDIT: I just notice the OMR 2000 xD Good job! You should use that to fly over here ✈️ 

P.S. Conversations on github issues should really be a thing

**Comment by FleetAdmiral** [comment]
> P.S. Conversations on github issues should really be a thing
I could not agree more!
To be honest, it was a team of 4 so i'm getting only 500 💸  - and i've already spent most of it to get myself a VIVE for some VR dev.
I have been getting accepted to a lot of hackathons down there, so once any of their reimbursement plans are good enough, i'll fly down ASAP 😛 .

**Comment by pranaygp** [comment]
Haha, that's fair

Shameless plug: HackIllinois might be able to reimburse you :)

**Comment by pranaygp** [comment]
I remember a bunch of people coming here from Waterloo last year, so, yeah. And if you do come here, I'll take you out for lunch//dinner

**Comment by pranaygp** [comment]
Ignore me. For some reason, when you said "down there", I thought you were in Canada, which was weird because I thought you went to school in India. Just realized you actually do :P

I'm embarrassed, but yeah, gonna be hard to get a university to reimburse you. But, I do remember this one guy from Spain who got into like 3 hackathons here, and had enough of a reimbursement to fly over (and just bus hop between each one)

Given that it costs almost 4 times as much to fly from India, just get into 12 hackathons here. Easy :)

**Comment by FleetAdmiral** [comment]
@pranaygp I have seniors who've been completely/sufficiently reimbursed by HACKMIT, so keeping my fingers crossed. 
I mean even if that doesn't work out, i guess i could just take a drop year, get accepted by a ton of hackathons, get all the reimbursements and then just cruise around the states, maybe buy some stocks from promising, yet ahead of their time startups/mid-tier business and then fly back after my year long vacay. Best part? Possible investment returns after 25 years! It's a win win 😃 .

Yea, that's probably not happening 😆 . Know what, how about you let me know when you come to down to Muscat (or Hyderabad, but that seems unlikely), and then maybe we can meet up?

**Comment by pranaygp** [comment]
Haha, that's definitely a lot more likely (me coming to Muscat)

Till then
